### ISSUE TITLE
Missing overlay on dark/black theme

### ISSUE THREAD

**Issue by eldainosor** [LiquidRemix/android_vendor_liquid#14]
This exposure is missing on Pie 

https://github.com/LiquidRemix/android_vendor_liquid/blob/118d5fa2b7c7514cf49272fcbfe96960bafea4ee/themes/Dark/DuiDialogs/res/values/projekt_colors.xml#L18

Hence it's causing this
![photo_2018-11-18_00-56-08](https://user-images.githubusercontent.com/11993364/48668459-ca1e2000-eacc-11e8-8c99-495ebc0a5adb.jpg)

can you add it on Pie? Thanks in advance!

**Comment by sayan7848** [comment]
I have made a PR for the same. Feel free to check it :-)

**Comment by eldainosor** [comment]
> I have made a PR for the same. Feel free to check it :-)

Your PR solved this issue! Thanks!
